// src/components/svelte/FinanceTracker/FinanceTracker.svelte
<script lang="ts">
  import FinanceCard from "../FinanceCard.svelte";
  import Expenses from "./Expenses/Expenses.svelte";
  import { expensesStore, incomesStore } from "./finance-tracker.stores";
  import Incomes from "./Incomes/Incomes.svelte";
  import TotalBalance from "./TotalBalance/TotalBalance.svelte";

  $: expenses = $expensesStore;
  $: incomes = $incomesStore;
</script>

<h1 class="text-center">Finance Tracker</h1>

<div>Range Date Picker here</div>

<div class="flex flex-wrap items-start justify-center gap-8">
  <FinanceCard title="Expense" headingElement="h2">
    <Expenses
      expenses={expenses}
      on:addExpense={({ detail }) => {
        expensesStore.update((state) => [...state, detail]);
      }}
    />
  </FinanceCard>

  <FinanceCard title="Income" headingElement="h2">
    <Incomes
      incomes={incomes}
      on:addExpense={({ detail }) => {
        incomesStore.update((state) => [...state, detail]);
      }}
    />
  </FinanceCard>
  <FinanceCard title="Total" headingElement="h2">
    <TotalBalance expenses={expenses} incomes={incomes} />
  </FinanceCard>
</div>

// src/components/vue/FinanceTracker/FinanceTracker.vue
<script lang="ts" setup>
import { ref } from "vue";
import ExpensesContent, { type Expense } from "./ExpensesContent/ExpensesContent.vue";
import FinanceCard from "./FinanceCard/FinanceCard.vue";
import type { Income } from "./IncomesContent/IncomesContent.vue";
import IncomesContent from "./IncomesContent/IncomesContent.vue";
import TotalBalance from "./TotalBalance/TotalBalance.vue";

const expenses = ref<Expense[]>([]);
const incomes = ref<Income[]>([]);
</script>

<template>
  <h1 class="text-center">Finance Tracker</h1>

  <div>Range Date Picker here</div>

  <div class="flex flex-wrap items-start justify-center gap-8">
    <FinanceCard title="Expense" heading-element="h2">
      <ExpensesContent :expenses="expenses" @add-expense="expenses.push($event)" />
    </FinanceCard>

    <FinanceCard title="Income" heading-element="h2">
      <IncomesContent :incomes="incomes" @add-income="incomes.push($event)" />
    </FinanceCard>

    <FinanceCard title="Total" heading-element="h2">
      <TotalBalance :incomes="incomes" :expenses="expenses" />
    </FinanceCard>
  </div>
</template>
